aws-cli-path: /home/ANT.AMAZON.COM/leegyuho/.local/bin/aws
client-burst: 20
client-qps: 10
client-timeout: 15000000000
client-timeout-string: 15s
clients: 2
command-after-create-add-ons: ""
command-after-create-add-ons-output-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.after-create-add-ons.out.log
command-after-create-add-ons-timeout: 180000000000
command-after-create-add-ons-timeout-string: 3m0s
command-after-create-cluster: ""
command-after-create-cluster-output-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.after-create-cluster.out.log
command-after-create-cluster-timeout: 180000000000
command-after-create-cluster-timeout-string: 3m0s
config-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.yaml
cw-namespace: aws-k8s-tester-eks
kubeconfig-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.kubeconfig.yaml
kubectl-commands-output-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.kubectl.sh
kubectl-download-url: https://storage.googleapis.com/kubernetes-release/release/v1.17.6/bin/linux/amd64/kubectl
kubectl-path: /tmp/kubectl-test-v1.17.6
log-color: true
log-color-override: false
log-level: info
log-outputs:
- stderr
- /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.log
name: eks-2020070622-spotlightga1
on-failure-delete: true
on-failure-delete-wait-seconds: 120
parameters:
  dhcp-options-domain-name: ""
  dhcp-options-domain-name-servers: null
  encryption-cmk-arn: ""
  encryption-cmk-create: true
  private-subnet-ids: null
  public-subnet-ids: null
  request-header-key: ""
  request-header-value: ""
  resolver-url: ""
  role-arn: ""
  role-cfn-stack-id: ""
  role-cfn-stack-yaml-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.role.cfn.yaml
  role-cfn-stack-yaml-s3-key: eks-2020070622-spotlightga1/default.role.cfn.yaml
  role-create: true
  role-managed-policy-arns: null
  role-name: eks-2020070622-spotlightga1-role
  role-service-principals: null
  signing-name: eks
  tags: null
  version: "1.16"
  version-value: 1.16
  vpc-cfn-stack-id: ""
  vpc-cfn-stack-yaml-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.vpc.cfn.yaml
  vpc-cfn-stack-yaml-s3-key: eks-2020070622-spotlightga1/default.vpc.cfn.yaml
  vpc-create: true
  vpc-id: ""
partition: aws
region: us-west-2
remote-access-commands-output-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.ssh.sh
remote-access-key-create: true
remote-access-key-name: eks-2020070622-spotlightga1-remote-access-key
remote-access-private-key-path: /tmp/waves5ywx5ha26r.insecure.key
s3-bucket-create: true
s3-bucket-create-keep: true
s3-bucket-lifecycle-expiration-days: 0
s3-bucket-name: eks-2020070622-spotlightga1-s3-bucket
status:
  aws-account-id: ""
  aws-credential-path: ""
  aws-iam-role-arn: ""
  aws-user-id: ""
  cluster-api-server-endpoint: ""
  cluster-arn: ""
  cluster-ca: ""
  cluster-ca-decoded: ""
  cluster-cfn-stack-id: ""
  cluster-cfn-stack-yaml-path: /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.cluster.cfn.yaml
  cluster-cfn-stack-yaml-s3-key: eks-2020070622-spotlightga1/default.cluster.cfn.yaml
  cluster-control-plane-security-group-id: ""
  cluster-oidc-issuer-arn: ""
  cluster-oidc-issuer-ca-thumbprint: ""
  cluster-oidc-issuer-host-path: ""
  cluster-oidc-issuer-url: ""
  cluster-status: null
  cluster-status-current: ""
  private-dns-to-ssh-config: {}
  server-version-info:
    buildDate: ""
    compiler: ""
    gitCommit: ""
    gitTreeState: ""
    gitVersion: ""
    goVersion: ""
    major: ""
    minor: ""
    platform: ""
    version-value: 0
  time-frame-create:
    complete-utc: "0001-01-01T00:00:00Z"
    complete-utc-rfc3339-nano: ""
    start-utc: "0001-01-01T00:00:00Z"
    start-utc-rfc3339-nano: ""
    took: 0
    took-string: ""
  time-frame-delete:
    complete-utc: "0001-01-01T00:00:00Z"
    complete-utc-rfc3339-nano: ""
    start-utc: "0001-01-01T00:00:00Z"
    start-utc-rfc3339-nano: ""
    took: 0
    took-string: ""
  up: false
total-hollow-nodes: 0
total-nodes: 0
