add-on-cni-vpc: null
client-burst: 20
client-qps: 10
client-timeout: 15000000000
client-timeout-string: 15s
clients: 2
command-after-create-add-ons: ""
command-after-create-add-ons-output-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.after-create-add-ons.out.log
command-after-create-add-ons-timeout: 180000000000
command-after-create-add-ons-timeout-string: 3m0s
command-after-create-cluster: ""
command-after-create-cluster-output-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.after-create-cluster.out.log
command-after-create-cluster-timeout: 180000000000
command-after-create-cluster-timeout-string: 3m0s
config-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.yaml
cw-namespace: aws-k8s-tester-eks
encryption:
  cmk-arn: ""
  cmk-create: true
kube-apiserver-max-requests-inflight: ""
kubeconfig-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.kubeconfig.yaml
kubectl-commands-output-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.kubectl.sh
kubectl-download-url: https://storage.googleapis.com/kubernetes-release/release/v1.20.7/bin/darwin/amd64/kubectl
kubectl-path: /tmp/kubectl-test-v1.20.7
log-color: true
log-color-override: ""
log-level: info
log-outputs:
- stderr
- /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.log
metadata:
  creationTimestamp: null
name: eks-2021071609-great6c9ncwa
on-failure-delete: true
on-failure-delete-wait-seconds: 120
partition: aws
region: us-west-2
remote-access-commands-output-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/eksconfig/default.ssh.sh
remote-access-key-create: true
remote-access-key-name: eks-2021071609-great6c9ncwa-remote-access-key
remote-access-private-key-path: /var/folders/xt/szh_n5x154x2hyhj0zkpd3qr0000gn/T/waterg01v38009f.insecure.key
request-header-key: ""
request-header-value: ""
resolver-url: ""
role:
  arn: ""
  create: true
  instance-profile-arn: ""
  instance-profile-name: ""
  managed-policy-arns:
  - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  - arn:aws:iam::aws:policy/AmazonSSMFullAccess
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
  - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
  name: eks-2021071609-great6c9ncwa-role
  policy-arn: ""
  policy-name: eks-2021071609-great6c9ncwa-policy
  service-principals:
  - ec2.amazonaws.com
  - eks.amazonaws.com
  - eks-fargate-pods.amazonaws.com
s3:
  bucket-create: true
  bucket-create-keep: true
  bucket-lifecycle-expiration-days: 0
  bucket-name: eks-2021071609-great6c9ncwa-s3-bucket
signing-name: eks
skip-delete-cluster-and-nodes: false
spec: {}
status:
  aws-account-id: ""
  aws-credential-path: ""
  aws-iam-role-arn: ""
  aws-user-id: ""
  cluster-api-server-endpoint: ""
  cluster-arn: ""
  cluster-ca: ""
  cluster-ca-decoded: ""
  cluster-oidc-issuer-arn: ""
  cluster-oidc-issuer-ca-thumbprint: ""
  cluster-oidc-issuer-host-path: ""
  cluster-oidc-issuer-url: ""
  cluster-status: null
  cluster-status-current: ""
  deleted-resources: {}
  private-dns-to-node-info: {}
  server-version-info:
    buildDate: ""
    compiler: ""
    gitCommit: ""
    gitTreeState: ""
    gitVersion: ""
    goVersion: ""
    major: ""
    minor: ""
    platform: ""
    version-value: 0
  time-frame-create:
    complete-utc: "0001-01-01T00:00:00Z"
    complete-utc-rfc3339-nano: ""
    start-utc: "0001-01-01T00:00:00Z"
    start-utc-rfc3339-nano: ""
    took: 0
    took-string: ""
  time-frame-delete:
    complete-utc: "0001-01-01T00:00:00Z"
    complete-utc-rfc3339-nano: ""
    start-utc: "0001-01-01T00:00:00Z"
    start-utc-rfc3339-nano: ""
    took: 0
    took-string: ""
  up: false
tags: null
total-hollow-nodes: 0
total-nodes: 0
version: "1.20"
version-value: 1.2
vpc:
  cidrs:
  - 10.0.0.0/16
  - 10.1.0.0/16
  - 10.2.0.0/16
  - 10.3.0.0/16
  create: true
  eip-allocation-ids: null
  id: ""
  internet-gateway-id: ""
  nat-gateway-ids: null
  node-group-security-group-id: ""
  node-group-security-group-name: eks-2021071609-great6c9ncwa-node-group-security-group
  private-route-table-ids: null
  private-subnet-cidrs:
  - 10.3.0.0/17
  - 10.3.128.0/17
  private-subnet-ids: null
  private-subnet-route-table-association-ids: null
  public-route-table-id: ""
  public-subnet-cidrs:
  - 10.0.0.0/16
  - 10.1.0.0/16
  - 10.2.0.0/16
  public-subnet-ids: null
  public-subnet-route-table-association-ids: null
  security-group-id: ""
