asgs:
  ec2-2021071718-wind8mffgayn-asg:
    ami-type: AL2_x86_64
    asg-desired-capacity: 1
    asg-max-size: 1
    asg-min-size: 1
    image-id: ""
    image-id-ssm-parameter: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    instanaces: null
    instance-type: c5.xlarge
    launch-template-name: ""
    logs: null
    name: ec2-2021071718-wind8mffgayn-asg
    remote-access-user-name: ec2-user
    ssm:
      document-command-ids: null
      document-commands: ""
      document-create: false
      document-execution-timeout-in-seconds: 3600
      document-name: ""
    time-frame-create:
      complete-utc: "0001-01-01T00:00:00Z"
      complete-utc-rfc3339-nano: ""
      start-utc: "0001-01-01T00:00:00Z"
      start-utc-rfc3339-nano: ""
      took: 0
      took-string: ""
    time-frame-delete:
      complete-utc: "0001-01-01T00:00:00Z"
      complete-utc-rfc3339-nano: ""
      start-utc: "0001-01-01T00:00:00Z"
      start-utc-rfc3339-nano: ""
      took: 0
      took-string: ""
    volume-size: 40
asgs-fetch-logs: true
asgs-logs-dir: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/ec2config/ec2-2021071718-wind8mffgayn-logs-remote
aws-account-id: ""
aws-credential-path: ""
aws-iam-role-arn: ""
aws-user-id: ""
config-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/ec2config/default.yaml
deleted-resources: {}
log-color: true
log-color-override: ""
log-level: info
log-outputs:
- stderr
- /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/ec2config/default.yaml.log
name: ec2-2021071718-wind8mffgayn
on-failure-delete: true
on-failure-delete-wait-seconds: 120
partition: aws
region: us-west-2
remote-access-commands-output-path: /Users/leegyuho/go/src/github.com/aws/aws-k8s-tester/ec2config/default.ssh.sh
remote-access-key-create: true
remote-access-key-name: ec2-2021071718-wind8mffgayn-key
remote-access-private-key-path: /var/folders/xt/szh_n5x154x2hyhj0zkpd3qr0000gn/T/breezemy7r.insecure.key
role:
  arn: ""
  create: true
  instance-profile-arn: ""
  instance-profile-name: ""
  managed-policy-arns:
  - arn:aws:iam::aws:policy/AmazonEC2FullAccess
  - arn:aws:iam::aws:policy/AmazonSSMFullAccess
  - arn:aws:iam::aws:policy/AmazonS3FullAccess
  name: ec2-2021071718-wind8mffgayn-role
  policy-arn: ""
  policy-name: ""
  service-principals:
  - ec2.amazonaws.com
s3:
  bucket-create: true
  bucket-create-keep: true
  bucket-lifecycle-expiration-days: 0
  bucket-name: ec2-2021071718-wind8mffgayn-s3-bucket
  dir: ec2-2021071718-wind8mffgayn
status: null
status-current: ""
time-frame-create:
  complete-utc: "0001-01-01T00:00:00Z"
  complete-utc-rfc3339-nano: ""
  start-utc: "0001-01-01T00:00:00Z"
  start-utc-rfc3339-nano: ""
  took: 0
  took-string: ""
time-frame-delete:
  complete-utc: "0001-01-01T00:00:00Z"
  complete-utc-rfc3339-nano: ""
  start-utc: "0001-01-01T00:00:00Z"
  start-utc-rfc3339-nano: ""
  took: 0
  took-string: ""
total-nodes: 1
up: false
vpc:
  cidrs:
  - 10.0.0.0/16
  - 10.1.0.0/16
  - 10.2.0.0/16
  - 10.3.0.0/16
  create: true
  eip-allocation-ids: null
  id: ""
  internet-gateway-id: ""
  nat-gateway-ids: null
  private-route-table-ids: null
  private-subnet-cidrs:
  - 10.3.0.0/17
  - 10.3.128.0/17
  private-subnet-ids: null
  private-subnet-route-table-association-ids: null
  public-route-table-id: ""
  public-subnet-cidrs:
  - 10.0.0.0/16
  - 10.1.0.0/16
  - 10.2.0.0/16
  public-subnet-ids: null
  public-subnet-route-table-association-ids: null
  security-group-id: ""
