#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

TRACE_LOG=trace.log
TEST_TIMEOUT=1800
BASH="/usr/bin/bash"
CURRENT_DIR=$(pwd)
SKIP_TESTS_SUBCOMMAND=${SKIP_TESTS_SUBCOMMAND:-""}

timeout -k 10 ${TEST_TIMEOUT} ${BASH} gpu_unit_tests/bash_unit -f tap ${SKIP_TESTS_SUBCOMMAND} -t gpu_unit_tests/${TRACE_LOG} gpu_unit_tests/tests/*test*.sh
