name: "CI"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - 'test/images/nvidia**'
      - 'test/images/neuron**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go build ./...
    - run: go test ./...
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go test -c -tags=e2e ./test/...
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./hack/free-disk-space.sh
    - run: docker build --build-arg=KUBERNETES_MINOR_VERSION=latest --file Dockerfile .
  build-image-efa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./hack/free-disk-space.sh
    - run: docker build --file test/images/efa/Dockerfile .
